on:
  push:

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Node
        run: |
          echo foobar
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
